export const items = [
  {
    id: 1,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Pear Tree Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#1a1aff"],
    imageUrl: "https://i.ibb.co/6yGDRNb/a-partridge-in-a-pear-tree.gif",
    imageThumb:
      "https://i.ibb.co/WK5JHmg/a-partridge-in-a-pear-tree-thumbnail.gif",
  },
  {
    id: 2,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Adoration of Kings Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/CJPsQmh/adoration-of-the-kings.gif",
    imageThumb: "https://i.ibb.co/tp75m9N/adoration-of-the-kings-thumbnail.gif",
  },
  {
    id: 3,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Afghan Flower T-shirt",
    price: 14.25,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/hLnSq4b/afghan-flower.gif",
    imageThumb: "https://i.ibb.co/pzL8MDk/afghan-flower-thumbnail.gif",
  },
  {
    id: 4,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Albania Flower Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/LQ5x8qY/albania-flower.gif",
    imageThumb: "https://i.ibb.co/4Tz1QHF/albania-flower-thumbnail.gif",
  },
  {
    id: 5,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Alsace Custom Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/MZFgmW1/alsace.gif",
    imageThumb: "https://i.ibb.co/DYL2WY5/alsace-thumbnail.gif",
  },
  {
    id: 6,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Altar Pice Custom Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/vDdfbvD/altar-piece.gif",
    imageThumb: "https://i.ibb.co/d6Psd1w/altar-piece-thumbnail.gif",
  },
  {
    id: 7,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Baby Seal Custom Print T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#1a1aff"],
    imageUrl: "https://i.ibb.co/DrHBNCy/baby-seal.gif",
    imageThumb: "https://i.ibb.co/XYR1n27/baby-seal-thumbnail.gif",
  },
  {
    id: 8,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Canda Goose Custom Prnt T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/kXYMbC5/canada-goose.gif",
    imageThumb: "https://i.ibb.co/thxbk1n/canada-goose-thumbnail.gif",
  },
  {
    id: 9,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Caribou Custom T-shirt",
    price: 14.25,
    sizes: ["S", "M"],
    color: ["#000", "#fff", "#ffff4d"],
    imageUrl: "https://i.ibb.co/w711dGK/caribou.gif",
    imageThumb: "https://i.ibb.co/zJ9z4YH/caribou-thumbnail.gif",
  },
  {
    id: 10,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Coat of Arms Custom T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/4Nkwp7h/coat-of-arms.gif",
    imageThumb: "https://i.ibb.co/rm3vpdJ/coat-of-arms-thumbnail.gif",
  },
  {
    id: 11,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Colobus Custom T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/j3bv4Hm/colobus.gif",
    imageThumb: "https://i.ibb.co/NVjdNNw/colobus-thumbnail.gif",
  },
  {
    id: 12,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Congo Rhino T-shirt",
    price: 14.25,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff", "#ffff4d"],
    imageUrl: "https://i.ibb.co/yd2w69F/congo-rhino.gif",
    imageThumb: "https://i.ibb.co/hCzmBDy/congo-rhino-thumbnail.gif",
  },
  {
    id: 13,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Equitorial Rhino T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/C2j9Zpv/equatorial-rhino.gif",
    imageThumb: "https://i.ibb.co/BPRmr9K/equatorial-rhino-thumbnail.gif",
  },
  {
    id: 14,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Gabon Flower T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/PDgj0q8/gabon-flower.gif",
    imageThumb: "https://i.ibb.co/GcKCLv6/gabon-flower-thumbnail.gif",
  },
  {
    id: 15,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Marianne Custom T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/XY2GfHS/marianne.gif",
    imageThumb: "https://i.ibb.co/ZLbsVN4/marianne-thumbnail.gif",
  },
  {
    id: 16,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Musk Ox T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/wdWm7xT/musk-ox.gif",
    imageThumb: "https://i.ibb.co/zNbDVdY/musk-ox-thumbnail.gif",
  },
  {
    id: 17,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Promise of Spring T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/HX4tv2c/the-promise-of-spring.gif",
    imageThumb: "https://i.ibb.co/Lvr3kx6/the-promise-of-spring-thumbnail.gif",
  },
  {
    id: 18,
    categories: ["Men", "Women"],
    subCategory: ["Shirts"],
    itemName: "Rupture Psyche T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/LSDLL9S/the-rapture-of-psyche.gif",
    imageThumb: "https://i.ibb.co/ZNLF3wm/the-rapture-of-psyche-thumbnail.gif",
  },
  {
    id: 20,
    categories: ["Men", "Women"],
    subCategory: ["Shirts"],
    itemName: "The Virgin Mary T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/MMGdgTV/the-virgin-mary.gif",
    imageThumb: "https://i.ibb.co/WBKWhHX/the-virgin-mary-thumbnail.gif",
  },
  {
    id: 21,
    categories: ["Men", "Women"],
    subCategory: ["Shirts"],
    itemName: "Thrilling Love Custom T-shirt",
    price: 14.25,
    sizes: ["M", "L"],
    color: ["#000", "#fff", "#1aff8c"],
    imageUrl: "https://i.ibb.co/X3kfbCm/thrilling-love.gif",
    imageThumb: "https://i.ibb.co/GsyYpw7/thrilling-love-thumbnail.gif",
  },
  {
    id: 22,
    categories: ["Men", "Women"],
    subCategory: ["Shirts"],
    itemName: "Torche T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#1aff8c"],
    imageUrl: "https://i.ibb.co/Dfr39hL/torch.gif",
    imageThumb: "https://i.ibb.co/BNbDZHY/torch-thumbnail.gif",
  },
  {
    id: 22,
    categories: ["Men", "Women"],
    subCategory: ["Shirts"],
    itemName: "Uruguay T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/yFMWdBc/uruguay-flower.gif",
    imageThumb: "https://i.ibb.co/T0CLwG8/uruguay-flower-thumbnail.gif",
  },
  {
    id: 22,
    categories: ["Men"],
    subCategory: ["Caps"],
    itemName: "Baseball Cap",
    price: 8.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg ",
    imageThumb: "https://i.ibb.co/5Tf59Ks/Cap-1-thumb.gif",
  },
  {
    id: 22,
    categories: ["Men"],
    subCategory: ["Caps", "Under Armor"],
    itemName: "Under Armor Baseball Cap",
    price: 8.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
    imageThumb: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
  },
];

export const catMen = [
  {
    id: 1,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Pear Tree Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#1a1aff"],
    imageUrl: "https://i.ibb.co/6yGDRNb/a-partridge-in-a-pear-tree.gif",
    imageThumb:
      "https://i.ibb.co/WK5JHmg/a-partridge-in-a-pear-tree-thumbnail.gif",
  },
  {
    id: 2,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Adoration of Kings Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/CJPsQmh/adoration-of-the-kings.gif",
    imageThumb: "https://i.ibb.co/tp75m9N/adoration-of-the-kings-thumbnail.gif",
  },
  {
    id: 3,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Afghan Flower T-shirt",
    price: 14.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/hLnSq4b/afghan-flower.gif",
    imageThumb: "https://i.ibb.co/pzL8MDk/afghan-flower-thumbnail.gif",
  },
  {
    id: 4,
    categories: ["Men"],
    subCategory: ["Shirts"],
    itemName: "Albania Flower Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/LQ5x8qY/albania-flower.gif",
    imageThumb: "https://i.ibb.co/4Tz1QHF/albania-flower-thumbnail.gif",
  },
  {
    id: 5,
    categories: ["Men"],
    subCategory: ["Caps"],
    itemName: "Baseball Cap",
    price: 8.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg ",
    imageThumb: "https://i.ibb.co/5Tf59Ks/Cap-1-thumb.gif",
  },
  {
    id: 6,
    categories: ["Men"],
    subCategory: ["Caps"],
    itemName: "Under Armor Baseball Cap",
    price: 8.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
    imageThumb: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
  },
  {
    id: 7,
    categories: ["Men"],
    subCategory: ["Hoodies"],
    itemName: "Comfortable Hoodie",
    price: 40.0,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/JQmYC9M/men-hoodies.gif",
    imageThumb: "",
  },
  {
    id: 8,
    categories: ["Men"],
    subCategory: ["Jacket"],
    itemName: "Denim Jacket for Men",
    price: 40.0,
    sizes: ["M", "L"],
    color: ["#000", "#e6ccb3"],
    imageUrl: "https://i.ibb.co/JQmYC9M/men-hoodies.gif",
    imageThumb: "",
  },
  {
    id: 9,
    categories: ["Men"],
    subCategory: ["Coat"],
    itemName: "Winter Coat for Men",
    price: 60.0,
    sizes: ["M", "L"],
    color: ["#000", "#e6ccb3"],
    imageUrl: "https://i.ibb.co/wsjYLjr/coat-men.gif",
    imageThumb: "",
  },
  {
    id: 10,
    categories: ["Men"],
    subCategory: ["Sweater"],
    itemName: "Woolen Sweater",
    price: 35.0,
    sizes: ["M", "L"],
    color: ["#000", "#e6ccb3"],
    imageUrl: "https://i.ibb.co/9Vs5JTC/Woolen-Sweater.gif",
    imageThumb: "",
  },
  {
    id: 11,
    categories: ["Men"],
    subCategory: ["Shorts"],
    itemName: "Summer Shorts",
    price: 34.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#e6ccb3"],
    imageUrl: "https://i.ibb.co/rG73TzR/shorts-men.gif",
    imageThumb: "",
  },
  {
    id: 12,
    categories: ["Men"],
    subCategory: ["Vest"],
    itemName: "Cotton Vest",
    price: 25.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#4da6ff"],
    imageUrl: "https://i.ibb.co/m4jFfw6/Vest-Men.gif",
    imageThumb: "",
  },
];

export const catWomen = [
  {
    id: 1,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Alsace Custom Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/MZFgmW1/alsace.gif",
    imageThumb: "https://i.ibb.co/DYL2WY5/alsace-thumbnail.gif",
  },
  {
    id: 2,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Altar Pice Custom Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/vDdfbvD/altar-piece.gif",
    imageThumb: "https://i.ibb.co/d6Psd1w/altar-piece-thumbnail.gif",
  },
  {
    id: 3,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Baby Seal Custom Print T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#1a1aff"],
    imageUrl: "https://i.ibb.co/DrHBNCy/baby-seal.gif",
    imageThumb: "https://i.ibb.co/XYR1n27/baby-seal-thumbnail.gif",
  },
  {
    id: 4,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Canda Goose Custom Prnt T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/kXYMbC5/canada-goose.gif",
    imageThumb: "https://i.ibb.co/thxbk1n/canada-goose-thumbnail.gif",
  },
  {
    id: 5,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Caribou Custom T-shirt",
    price: 14.0,
    sizes: ["S", "M"],
    color: ["#000", "#fff", "#ffff4d"],
    imageUrl: "https://i.ibb.co/w711dGK/caribou.gif",
    imageThumb: "https://i.ibb.co/zJ9z4YH/caribou-thumbnail.gif",
  },
  {
    id: 6,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Coat of Arms Custom T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/4Nkwp7h/coat-of-arms.gif",
    imageThumb: "https://i.ibb.co/rm3vpdJ/coat-of-arms-thumbnail.gif",
  },
  {
    id: 7,
    categories: ["Women"],
    subCategory: ["Shirts"],
    itemName: "Colobus Custom T-shirt",
    price: 14.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/j3bv4Hm/colobus.gif",
    imageThumb: "https://i.ibb.co/NVjdNNw/colobus-thumbnail.gif",
  },
  {
    id: 8,
    categories: ["Women"],
    subCategory: ["Cap"],
    itemName: "Floral Cap",
    price: 14.0,
    sizes: ["S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/k4RFC31/cap-women-1.gif",
    imageThumb: "",
  },
  {
    id: 9,
    categories: ["Women"],
    subCategory: ["Skirt"],
    itemName: "Denim Skirt",
    price: 14.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#1a8cff"],
    imageUrl: "https://i.ibb.co/k4RFC31/cap-women-1.gif",
    imageThumb: "",
  },
  {
    id: 9,
    categories: ["Women"],
    subCategory: ["Crop Top"],
    itemName: "Cute Pineapple Print Crop top",
    price: 14.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#1a8cff"],
    imageUrl: "https://i.ibb.co/tHkMqFx/crop-top.gif",
    imageThumb: "",
  },
  {
    id: 10,
    categories: ["Women"],
    subCategory: ["Tube Top"],
    itemName: "Ribbed Flounced Tube Top",
    price: 25.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ff4d4d"],
    imageUrl: "https://i.ibb.co/q1mrhnT/Tube-Top.gif",
    imageThumb: "",
  },
  {
    id: 11,
    categories: ["Women"],
    subCategory: ["Sweater"],
    itemName: "Alpaca turtleneck sweater",
    price: 25.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ffe6e6"],
    imageUrl: "https://i.ibb.co/q1mrhnT/Tube-Top.gif",
    imageThumb: "",
  },
  {
    id: 12,
    categories: ["Women"],
    subCategory: ["Trousers"],
    itemName: "Solid Cropped Peg Trousers",
    price: 35.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ffe6e6"],
    imageUrl: "https://i.ibb.co/myfkdP2/Women-trousers.gif",
    imageThumb: "",
  },
];

export const catKids = [
  {
    id: 1,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Congo Rhino T-shirt",
    price: 14.25,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff", "#ffff4d"],
    imageUrl: "https://i.ibb.co/yd2w69F/congo-rhino.gif",
    imageThumb: "https://i.ibb.co/hCzmBDy/congo-rhino-thumbnail.gif",
  },
  {
    id: 2,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Equitorial Rhino T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/C2j9Zpv/equatorial-rhino.gif",
    imageThumb: "https://i.ibb.co/BPRmr9K/equatorial-rhino-thumbnail.gif",
  },
  {
    id: 3,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Gabon Flower T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/PDgj0q8/gabon-flower.gif",
    imageThumb: "https://i.ibb.co/GcKCLv6/gabon-flower-thumbnail.gif",
  },
  {
    id: 4,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Marianne Custom T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/XY2GfHS/marianne.gif",
    imageThumb: "https://i.ibb.co/ZLbsVN4/marianne-thumbnail.gif",
  },
  {
    id: 5,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Musk Ox T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M", "L"],
    color: ["#000", "#fff", "#3377ff"],
    imageUrl: "https://i.ibb.co/wdWm7xT/musk-ox.gif",
    imageThumb: "https://i.ibb.co/zNbDVdY/musk-ox-thumbnail.gif",
  },
  {
    id: 6,
    categories: ["Kids"],
    subCategory: ["Shirts"],
    itemName: "Promise of Spring T-shirt",
    price: 14.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/HX4tv2c/the-promise-of-spring.gif",
    imageThumb: "https://i.ibb.co/Lvr3kx6/the-promise-of-spring-thumbnail.gif",
  },
  {
    id: 7,
    categories: ["Kids"],
    subCategory: ["Cap"],
    itemName: "Net Sports Cap",
    price: 5.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/Sy2xhkq/net-sports-cap.gif",
    imageThumb: "https://i.ibb.co/G2v6r8H/net-sports-cap-thumb.gif",
  },
  {
    id: 8,
    categories: ["Kids"],
    subCategory: ["Cap"],
    itemName: "Floral Cap",
    price: 7.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/k4RFC31/cap-women-1.gif",
    imageThumb: "",
  },
  {
    id: 9,
    categories: ["Kids"],
    subCategory: ["Backpack"],
    itemName: "Kids Eco Backpack",
    price: 75.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/72cVm2X/KIDS-ECO-ORANGE-1.gif",
    imageThumb: "",
  },
  {
    id: 10,
    categories: ["Kids"],
    subCategory: ["Sweater"],
    itemName: "Kids Holiday Sweater",
    price: 18.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/ThfjFhG/kids-sweater.gif",
    imageThumb: "",
  },
  {
    id: 11,
    categories: ["Kids"],
    subCategory: ["Pants"],
    itemName: "Hoofit Pants for Children",
    price: 27.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/HrPyT1Q/hoofit-pant-Kids.gif",
    imageThumb: "",
  },
  {
    id: 12,
    categories: ["Kids"],
    subCategory: ["Skirt"],
    itemName: "Cotton Floral Skirt",
    price: 27.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#fff"],
    imageUrl: "https://i.ibb.co/ysWzg6j/Skirt-Kid.gif",
    imageThumb: "",
  },
  {
    id: 13,
    categories: ["Kids"],
    subCategory: ["Hat"],
    itemName: "Hiking Hat for Kids",
    price: 13.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ff66b3"],
    imageUrl: "https://i.ibb.co/7Jf9B4S/hat-kids.gif",
    imageThumb: "",
  },
  {
    id: 14,
    categories: ["Kis"],
    subCategory: ["Shoes"],
    itemName: "Light School Shoes",
    price: 35.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/bFdLPbH/kids-shoes.gif",
    imageThumb: "",
  },
];

export const catShoes = [
  {
    id: 1,
    categories: ["Shoes"],
    subCategory: ["Kids Shoes"],
    itemName: "Light School Shoes",
    price: 35.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/bFdLPbH/kids-shoes.gif",
    imageThumb: "",
  },
  {
    id: 2,
    categories: ["Shoes"],
    subCategory: ["Women's Heels"],
    itemName: "Ankle Strap High Heels",
    price: 35.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/d0z6T4V/heels-women.gif",
    imageThumb: "",
  },
  {
    id: 3,
    categories: ["Shoes"],
    subCategory: ["Sports"],
    itemName: "World Balance Sports Shoes",
    price: 35.0,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/svLzVKW/sports-shoes.gif",
    imageThumb: "",
  },
  {
    id: 4,
    categories: ["Shoes"],
    subCategory: ["Sneakers"],
    itemName: "Low Cut Sneakers",
    price: 21.0,
    sizes: ["S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/SXZzpvr/sneakers.gif",
    imageThumb: "",
  },
  {
    id: 5,
    categories: ["Shoes"],
    subCategory: ["Boots"],
    itemName: "Leather Boots",
    price: 21.0,
    sizes: ["S", "M"],
    color: ["#000", "#663300"],
    imageUrl: "https://i.ibb.co/X7rRbzS/Boots.gif",
    imageThumb: "",
  },
  {
    id: 6,
    categories: ["Shoes"],
    subCategory: ["Trekking"],
    itemName: "Trekking Boots",
    price: 21.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#663300"],
    imageUrl: "https://i.ibb.co/9qvCCNK/Trekking-Boots.gif",
    imageThumb: "",
  },
  {
    id: 7,
    categories: ["Shoes"],
    subCategory: ["Sandals"],
    itemName: "Breathable Sandals",
    price: 18.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#663300"],
    imageUrl: "https://i.ibb.co/tKhbm2Q/Sandals.gif",
    imageThumb: "",
  },
  {
    id: 8,
    categories: ["Shoes"],
    subCategory: ["Flip Flop"],
    itemName: "Pro Durable Flip Flop",
    price: 18.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#663300"],
    imageUrl: "https://i.ibb.co/G7zbvVF/flipflop.gif",
    imageThumb: "",
  },
];

export const catBrands = [
  {
    id: 1,
    categories: ["Brand"],
    subCategory: ["Under Armor"],
    itemName: "Under Armor Baseball Cap",
    price: 8.25,
    sizes: ["XS", "S", "M"],
    color: ["#000", "#fff", "#ff0000"],
    imageUrl: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
    imageThumb: "https://i.ibb.co/vZJSNJQ/41r-RYvvzr-EL.jpg",
  },
  {
    id: 2,
    categories: ["Brand"],
    subCategory: ["Converse"],
    itemName: "Chuck Taylor Sneakers",
    price: 21.0,
    sizes: ["S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/SXZzpvr/sneakers.gif",
    imageThumb: "",
  },
  {
    id: 3,
    categories: ["Brand"],
    subCategory: ["Uniqlo"],
    itemName: "Uniqlo Cotton Crew Neck T-shirt",
    price: 21.0,
    sizes: ["S", "M"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/PZ0TxLW/uniqlo.png",
    imageThumb: "",
  },
  {
    id: 4,
    categories: ["Brand"],
    subCategory: ["H&M"],
    itemName: "H&M FRIENDS T-shirt",
    price: 21.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/k99Kr7j/H-M.gif",
    imageThumb: "",
  },
  {
    id: 5,
    categories: ["Brand"],
    subCategory: ["Levis"],
    itemName: "Levi's Classic T-shirt",
    price: 21.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/nfPGKV6/Levi.gif",
    imageThumb: "",
  },
  {
    id: 6,
    categories: ["Brand"],
    subCategory: ["Addidas"],
    itemName: "Addidas Trefoil T-shirt",
    price: 35.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#ff0000"],
    imageUrl: "https://i.ibb.co/nkk11ZT/Adiddas.gif",
    imageThumb: "",
  },
  {
    id: 8,
    categories: ["Brand"],
    subCategory: ["GAP"],
    itemName: "GAP Iron Man T-sirt",
    price: 32.0,
    sizes: ["S", "M", "L"],
    color: ["#000", "#800000"],
    imageUrl: "https://i.ibb.co/nkk11ZT/Adiddas.gif",
    imageThumb: "",
  },
];

export const categories = [
  {
    id: "c1",
    name: "Women",
    subcat: [
      {
        id: "wsb1",
        name: "Caps and Hats",
      },
      {
        id: "wsb2",
        name: "Headbands",
      },
      {
        id: "wsb3",
        name: "Bags",
      },
      {
        id: "wsb4",
        name: "Head Tie / Scarves",
      },
      {
        id: "wsb5",
        name: "Shirts",
      },
      {
        id: "wsb6",
        name: "Bottoms",
      },
      {
        id: "wsb7",
        name: "Underwear",
      },
      {
        id: "wsb8",
        name: "Crop Tops",
      },
      {
        id: "wsb9",
        name: "Sweaters",
      },
      {
        id: "ksb10",
        name: "Accessories",
      },
      {
        id: "wsb11",
        name: "Tube Top",
      },
      {
        id: "wsb12",
        name: "Pants/Trousers",
      },
      {
        id: "wsb13",
        name: "Skirts",
      },
      {
        id: "wsb14",
        name: "Shorts",
      },
      {
        id: "wsb15",
        name: "Sarong",
      },
      {
        id: "wsb16",
        name: "Tights and Leggings",
      },
      {
        id: "wsb17",
        name: "Socks",
      },
      {
        id: "wsb18",
        name: "Dresses/Gowns",
      },
    ],
  },
  {
    id: "c2",
    name: "Men",
    subcat: [
      {
        id: "msb1",
        name: "Shirts",
      },
      {
        id: "msb2",
        name: "Pants",
      },
      {
        id: "msb3",
        name: "Caps and Hats",
      },
      {
        id: "msb4",
        name: "Jeans",
      },
      {
        id: "msb5",
        name: "Shorts",
      },
      {
        id: "msb6",
        name: "Coats",
      },
      {
        id: "msb7",
        name: "Jackets",
      },
      {
        id: "msb8",
        name: "Hoodies",
      },
      {
        id: "msb9",
        name: "Underwear",
      },
      {
        id: "msb10",
        name: "Socks",
      },
      {
        id: "msb11",
        name: "Sweaters",
      },
      {
        id: "msb12",
        name: "Vest",
      },
      {
        id: "msb13",
        name: "Ties",
      },
      {
        id: "msb14",
        name: "Accessories",
      },
    ],
  },
  {
    id: "c3",
    name: "Kids",
    subcat: [
      {
        id: "ksb1",
        name: "Bags",
      },
      {
        id: "ksb2",
        name: "Caps and Hats",
      },
      {
        id: "ksb3",
        name: "Kids Headbands",
      },
      {
        id: "ksb4",
        name: "Shirts",
      },
      {
        id: "ksb5",
        name: "Underwear",
      },
      {
        id: "ksb6",
        name: "Bottoms",
      },
      {
        id: "ksb7",
        name: "Sweaters",
      },
      {
        id: "ksb8",
        name: "Crop Tops",
      },
      {
        id: "ksb9",
        name: "Sweaters",
      },
      {
        id: "ksb10",
        name: "Accessories",
      },
      {
        id: "ksb11",
        name: "Tube Top",
      },
      {
        id: "ksb12",
        name: "Pants/Trousers",
      },
      {
        id: "ksb13",
        name: "Skirts",
      },
      {
        id: "ksb14",
        name: "Shorts",
      },
    ],
  },
  {
    id: "c4",
    name: "Shoes",
    subcat: [
      {
        id: "ssb1",
        name: "Sports Shoes",
      },
      {
        id: "ssb2",
        name: "Sneakers",
      },
      {
        id: "ssb3",
        name: "Hiking Boots",
      },
      {
        id: "ssb4",
        name: "Running Shoes",
      },
      {
        id: "ssb5",
        name: "Combat Boots",
      },
      {
        id: "ssb6",
        name: "School Shoes",
      },
      {
        id: "ssb7",
        name: "Women's Heels",
      },
      {
        id: "ssb8",
        name: "Kids Shoes",
      },
    ],
  },
  {
    id: "c5",
    name: "Brands",
    subcat: [
      {
        id: "bsb1",
        name: "Armani",
      },
      {
        id: "bsb2",
        name: "adidas",
      },
      {
        id: "bsb3",
        name: "adidas Originals",
      },
      {
        id: "bsb4",
        name: "Calvin Klein",
      },
      {
        id: "bsb5",
        name: "Crocs",
      },
      {
        id: "bsb6",
        name: "DC Comics",
      },
      {
        id: "bsb7",
        name: "Havaianas",
      },
      {
        id: "bsb8",
        name: "H&M",
      },
      {
        id: "bsb9",
        name: "Uniqlo",
      },
      {
        id: "bsb10",
        name: "Under Armour",
      },
      {
        id: "bsb11",
        name: "The North Face",
      },
      {
        id: "bsb12",
        name: "Levi Strauss",
      },
      {
        id: "bsb13",
        name: "Puma",
      },
      {
        id: "bsb14",
        name: "Tommy Hilfiger",
      },
      {
        id: "bsb15",
        name: "Gap",
      },
      {
        id: "bsb16",
        name: "Old Navy",
      },
      {
        id: "bsb17",
        name: "Skechers",
      },
    ],
  },
];

// export const subcategories = [
//     {
//         id: 'sc1',
//         category: 'c1',

//     }
// ]
