export const categoryActionTypes = {
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
  SET_SHOP_ITEMS: "SET_SHOP_ITEMS",
  SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
  SET_SUB_CATEGORIES: "SET_SUB_CATEGORIES",
  SET_SUBCAT_FILTER: "SET_SUBCAT_FILTER",
  SET_PRIZESIZE_FILTER: "SET_PRIZESIZE_FILTER",
};
