export const categoryActionTypes = {
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
  SET_SHOP_ITEMS: "SET_SHOP_ITEMS",
  SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
  SET_SUB_CATEGORIES: "SET_SUB_CATEGORIES",
};
