export const cartActionTypes = {
  SET_ITEM_COUNT: "SET_ITEM_COUNT",
  SET_TOTAL_PRICE: "SET_TOTAL_PRICE",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  UPDATE_CART_ITEM: "UPDATE_ITEM",
};
